import CryptoKit
import Foundation
import Security

// MARK: - Versioned HMAC key storage

/// Storage seam for the approval HMAC key. The production implementation is
/// backed by macOS Keychain; tests can inject an in-memory implementation
/// without touching a developer's real Keychain.
public protocol HMACKeyMaterialBackend: Sendable {
    func read(service: String, account: String, accessGroup: String?) throws -> Data?
    func write(_ data: Data, service: String, account: String, accessGroup: String?) throws
}

/// Versioned Keychain-backed key provider for local approval authorities.
///
/// The key is ordinary 256-bit HMAC material stored as a generic-password
/// item. Secure Enclave does not provide direct HMAC operations, so this class
/// deliberately does not claim Secure Enclave-backed HMAC. A future asymmetric
/// issuer may use the enclave separately for process authentication.
public actor KeychainHMACKeyStore {
    public struct Version: RawRepresentable, Hashable, Codable, Sendable, Comparable {
        public let rawValue: Int

        public init(rawValue: Int) {
            self.rawValue = rawValue
        }

        public static let v1 = Version(rawValue: 1)
        public static let current = Version.v1

        public static func < (lhs: Version, rhs: Version) -> Bool {
            lhs.rawValue < rhs.rawValue
        }
    }

    public enum StoreError: Error, Sendable, Equatable, CustomStringConvertible {
        case invalidVersion
        case corruptKeyMaterial(version: Version, byteCount: Int)
        case keyUnavailable(version: Version)
        case backend(String)

        public var description: String {
            switch self {
            case .invalidVersion:
                return "HMAC key version must be positive"
            case .corruptKeyMaterial(let version, let byteCount):
                return "HMAC key \(version.rawValue) has invalid key material (\(byteCount) bytes; expected 32)"
            case .keyUnavailable(let version):
                return "HMAC key \(version.rawValue) was not available after provisioning"
            case .backend(let message):
                return "HMAC key backend failed: \(message)"
            }
        }
    }

    public static let service = "com.hive.browser.approval-hmac"

    private let accessGroup: String?
    private let backend: any HMACKeyMaterialBackend

    public init(
        accessGroup: String? = nil,
        backend: (any HMACKeyMaterialBackend)? = nil
    ) {
        self.accessGroup = accessGroup
        self.backend = backend ?? KeychainHMACBackend()
    }

    /// Loads an existing versioned key, or provisions it once if absent.
    /// Existing malformed material is never overwritten: losing an old key
    /// would make pending signed recovery records unrecoverable.
    public func loadOrCreateKey(version: Version = .current) throws -> SymmetricKey {
        guard version.rawValue > 0 else { throw StoreError.invalidVersion }
        if let existing = try loadKey(version: version) {
            return existing
        }

        let material = SymmetricKey(size: .bits256)
        let bytes = material.withUnsafeBytes { Data($0) }
        do {
            try backend.write(
                bytes,
                service: Self.service,
                account: account(for: version),
                accessGroup: accessGroup
            )
        } catch {
            throw StoreError.backend(String(describing: error))
        }

        // A concurrent process may have won provisioning. Always read back the
        // persisted value instead of assuming the generated bytes were stored.
        guard let persisted = try loadKey(version: version) else {
            throw StoreError.keyUnavailable(version: version)
        }
        return persisted
    }

    /// Loads a version without provisioning it. Useful during rotation and
    /// recovery when callers must distinguish missing from newly created keys.
    public func loadKey(version: Version = .current) throws -> SymmetricKey? {
        guard version.rawValue > 0 else { throw StoreError.invalidVersion }
        let data: Data?
        do {
            data = try backend.read(
                service: Self.service,
                account: account(for: version),
                accessGroup: accessGroup
            )
        } catch {
            throw StoreError.backend(String(describing: error))
        }
        guard let data else { return nil }
        guard data.count == 32 else {
            throw StoreError.corruptKeyMaterial(version: version, byteCount: data.count)
        }
        return SymmetricKey(data: data)
    }

    /// Constructs an authority using a stable versioned key. The authority
    /// embeds the version into signed claims so rotation is explicit.
    public func makeAuthority(
        issuerID: String = "hive-approval-controller",
        version: Version = .current
    ) throws -> RetentionCapabilityAuthority {
        let key = try loadOrCreateKey(version: version)
        return try RetentionCapabilityAuthority(
            key: key,
            issuerID: issuerID,
            keyVersion: version.rawValue
        )
    }

    private func account(for version: Version) -> String {
        "approval-hmac-v\(version.rawValue)"
    }
}

private struct KeychainHMACBackend: HMACKeyMaterialBackend {
    func read(service: String, account: String, accessGroup: String?) throws -> Data? {
        var query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: account,
            kSecMatchLimit as String: kSecMatchLimitOne,
            kSecReturnData as String: true,
        ]
        if let accessGroup { query[kSecAttrAccessGroup as String] = accessGroup }

        var result: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &result)
        if status == errSecItemNotFound { return nil }
        guard status == errSecSuccess else { throw KeychainHMACBackendError.status(status) }
        return result as? Data
    }

    func write(_ data: Data, service: String, account: String, accessGroup: String?) throws {
        var query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: account,
            kSecValueData as String: data,
            kSecAttrLabel as String: "Hive Browser Approval HMAC — \(account)",
            kSecAttrAccessible as String: kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly,
        ]
        if let accessGroup { query[kSecAttrAccessGroup as String] = accessGroup }

        let status = SecItemAdd(query as CFDictionary, nil)
        if status == errSecDuplicateItem {
            // Another process provisioned the same version. The caller reads
            // back the winner and never replaces existing key material.
            return
        }
        guard status == errSecSuccess else { throw KeychainHMACBackendError.status(status) }
    }
}

private enum KeychainHMACBackendError: Error, CustomStringConvertible {
    case status(OSStatus)

    var description: String {
        switch self {
        case .status(let status): return "Security framework status \(status)"
        }
    }
}
