//
//  BrowserState+Reader.swift
//  Hive
//
//  Carved out of BrowserState.swift by scripts/split_browser_state.py.
//  Pure extension split, no behavior change. Access was widened from
//  `private`/`private(set)` to internal so the cross-file extensions
//  compile; this app target has no external API surface.
//
//  Sections: - Reader Mode
//

import SwiftUI
import Observation
import CefSwiftUI
import CefKit
import HiveCore
import AppKit


// MARK: - BrowserState + Reader

@MainActor
extension BrowserState {


    // MARK: - Reader Mode
    // Safari-style: injects CSS/JS that hides non-content elements and applies
    // clean typography to the page in-place. No text extraction needed.

    func toggleReaderMode() {
        if isReaderMode {
            // Exit reader mode — reload the original page through the
            // tab-scoped navigation boundary so an older load cannot win.
            isReaderMode = false
            readerWordCount = nil
            reload()
            return
        }
        // Entering reader mode requires a real web page. Guard here (not just
        // at each UI surface) so ⌘⇧R and other keyboard paths can never inject
        // reader CSS into a chrome/start/blank page.
        guard canUseWebPageActions else { return }
        guard let model = activeModel else { return }
        // A fresh article never shows the previous one's count; the injected
        // JS reports the real number right after injection.
        readerWordCount = nil
        // Inject reader mode CSS + element hiding
        model.executeJavaScript(readerModeJS())
        withAnimation(isReduceMotionEnabled ? nil : HiveDesign.Animation.spring) {
            isReaderMode = true
        }
    }


    /// Safari-style reader: hide everything except the main content area,
    /// then apply clean typography. The stylesheet is generated by the pure
    /// HiveCore `ReaderStyle` model from the current font scale + theme (baked
    /// in as `:root` custom-property defaults), so the first paint already
    /// matches the saved appearance; the variable script pins explicit themes
    /// over the auto dark media override.
    func readerModeJS() -> String {
        let cssLiteral: String
        if let data = try? JSONEncoder().encode(readerStyle.readerCSS()),
           let json = String(data: data, encoding: .utf8) {
            cssLiteral = json
        } else {
            cssLiteral = "\"\""
        }
        let varScript = readerStyle.cssVariableUpdateScript()
        return """
        (function() {
            if (document.getElementById('hive-reader-style')) {
                // Already applied — remove reader mode
                var s = document.getElementById('hive-reader-style');
                if (s) s.remove();
                var pr = document.getElementById('hive-reader-progress');
                if (pr) pr.remove();
                if (window.__hiveReaderProgress) {
                    window.removeEventListener('scroll', window.__hiveReaderProgress);
                    window.removeEventListener('resize', window.__hiveReaderProgress);
                    delete window.__hiveReaderProgress;
                }
                document.querySelectorAll('[data-hive-hidden]').forEach(function(el) {
                    el.style.display = '';
                    el.removeAttribute('data-hive-hidden');
                });
                document.body.style.overflow = '';
                return;
            }
            var style = document.createElement('style');
            style.id = 'hive-reader-style';
            style.textContent = \(cssLiteral);
            document.head.appendChild(style);
            \(varScript)

            // Hide navigation, sidebars, ads, comments, and non-article elements
            var selectors = [
                'nav', 'header', 'footer', 'aside',
                '.nav', '.navbar', '.navigation', '.sidebar', '.side-bar',
                '.footer', '.site-footer', '.page-footer',
                '.header', '.site-header', '.page-header',
                '.ad', '.ads', '.advertisement', '.banner',
                '.comments', '.comment-section', '#comments',
                '.related-posts', '.recommended', '.sidebar-widget',
                '.social-share', '.share-buttons',
                '.newsletter', '.subscribe', '.popup', '.modal'
            ];
            selectors.forEach(function(sel) {
                document.querySelectorAll(sel).forEach(function(el) {
                    if (!el.hasAttribute('data-hive-hidden')) {
                        el.setAttribute('data-hive-hidden', '1');
                        el.style.display = 'none';
                    }
                });
            });

            // Try to find the main content and show only that
            var content = document.querySelector('article, [role="main"], main, .post-content, .article-content, .entry-content, .markdown-body, .prose');
            if (content) {
                // Hide siblings that aren't the content
                var parent = content.parentElement;
                if (parent) {
                    Array.from(parent.children).forEach(function(child) {
                        if (child !== content && !child.hasAttribute('data-hive-hidden')) {
                            child.setAttribute('data-hive-hidden', '1');
                            child.style.display = 'none';
                        }
                    });
                }
            }

            document.body.style.overflow = 'auto';
            window.scrollTo(0, 0);

            // Word count (Safari convention): count the words in the article
            // content and report them over the console bridge so the Reader
            // bar can show "~N words". Words are whitespace-delimited tokens
            // with punctuation stripped — close enough for a reading-time hint.
            var wordCount = 0;
            var countRoot = content || document.body;
            var text = (countRoot.innerText || countRoot.textContent || '').trim();
            if (text) {
                var tokens = text.split(/\\s+/);
                for (var i = 0; i < tokens.length; i++) {
                    var w = tokens[i].replace(/^[^\\p{L}\\p{N}]+|[^\\p{L}\\p{N}]+$/gu, '');
                    if (w) wordCount++;
                }
            }
            if (typeof console !== 'undefined' && console.log) {
                console.log('HIVE_READER_WORDS|' + wordCount);
            }

            // Reading progress (Safari/Arc convention): a thin accent bar pinned
            // to the top of the viewport that fills as the article is read.
            var progress = document.createElement('div');
            progress.id = 'hive-reader-progress';
            progress.style.cssText = 'position:fixed;top:0;left:0;height:3px;width:0;z-index:2147483647;pointer-events:none;background:var(--hive-r-link, #60a5fa);transition:width .08s linear;';
            document.body.appendChild(progress);
            function updateProgress() {
                var max = document.documentElement.scrollHeight - window.innerHeight;
                var pct = max > 0 ? Math.min(100, Math.max(0, (window.scrollY / max) * 100)) : 0;
                progress.style.width = pct + '%';
            }
            window.addEventListener('scroll', updateProgress, { passive: true });
            window.addEventListener('resize', updateProgress, { passive: true });
            window.__hiveReaderProgress = updateProgress;
            updateProgress();
        })();
        """
    }


    /// Steps the reader font size along the HiveCore ladder (clamped).
    /// `readerStyle.didSet` persists it and live-updates an open reader page.
    func adjustReaderFontScale(by delta: Double) {
        readerStyle = ReaderStyle(fontScale: readerStyle.fontScale + delta, theme: readerStyle.theme, fontFamily: readerStyle.fontFamily)
    }


    /// Switches the reader color theme. `readerStyle.didSet` persists it and
    /// live-updates an open reader page.
    func setReaderTheme(_ theme: ReaderTheme) {
        readerStyle = ReaderStyle(fontScale: readerStyle.fontScale, theme: theme, fontFamily: readerStyle.fontFamily)
    }

    /// Toggles the reader font family (serif / sans, Safari parity).
    /// `readerStyle.didSet` persists it and live-updates an open reader page.
    func setReaderFontFamily(_ family: ReaderFontFamily) {
        readerStyle = ReaderStyle(fontScale: readerStyle.fontScale, theme: readerStyle.theme, fontFamily: family)
    }


    func sendGeminiMessage(_ text: String, referencedTabIDs: Set<String> = []) {
        let userMsg = GeminiMessage(role: .user, text: text)
        geminiMessages.append(userMsg)

        // Use the Swarm agent pipeline with hot memory context.
        // Thread explicit @tab references through so the orchestrator
        // actually receives the referenced tabs' context (Dia-parity).
        generateOrchestratedResponse(
            role: .summarizer,
            intent: text,
            maxTokens: 512,
            explicitTabIDs: referencedTabIDs
        )
    }
}
